### PR TITLE
Transform via Sphinx/Hawkmoth extensions

### PR DESCRIPTION
**Pull request by jnikula**
FYI @BrunoMSantos, this is what I'm drafting. Please don't waste review cycles on this yet, it's just to give you an idea.

### CODE REVIEW

**Comment by BrunoMSantos** [comment]
I see. It fits in! And you're planning this for the next release, is that right? Wondering if I should just leave `cautodoc_transformations` alone in the other branch.

**Comment by jnikula** [comment]
> I see. It fits in! And you're planning this for the next release, is that right? Wondering if I should just leave `cautodoc_transformations` alone in the other branch.

I guess more than anything I'd like to avoid first renaming `cautodoc_transformations` to `hawkmoth_transformations`, with deprecations, and then deprecating the both of them in favour of this. There's been enough confusion around this feature already.

The primary uncertainty I have around this is the signature of the event. What should be passed to `hawkmoth-process-docstring`? I admit my Python knowledge falls short of how to ensure forward/backward compatibility of an interface like this.

**Comment by jnikula** [comment]
I realized it's possible to implement the `cautodoc_transformations` stuff as a built-in extension using the `hawkmoth-process-docstring` event. I think it's pretty clean this way (pushed the implementation). I think `cautodoc_transformations` should stay, and only the other configs should be converted to `hawkmoth_*`.

**Comment by BrunoMSantos** [comment]
Sounds good. I'll rebase my work accordingly.

**Pull request closed without merging**
