### PR TITLE
GitHub actions update

### PR DESCRIPTION
**Pull request by jnikula**
Minor cleanups

### CODE REVIEW

**Comment by jnikula** [comment]
Ugh, some issues with specifying Python version and installing python3-clang, which can't be found when using Python 3.10. I give up.

**Comment by BrunoMSantos** [comment]
Hmm, what's the default Python version?

When installing Clang through apt, it will most likely install it to a folder like `/lib/python3.10/site-packages/` (replace 3.10 by whatever Python version is default). Naturally that folder will only be in the search path for the respective version of Python.

Before considering ugly hacks, does it solve anything if we also add `clang` to the `requirements.txt` file? Presumably it will install the bindings for the right version and still be able to find `libclang` from the apt package.

**Comment by BrunoMSantos** [comment]
Of course that the clang bindings installed that way are not 'official'...

By the way, I'd also contest the recommendation to specify the version honestly. v3.10 might be a bold thing to do today, it will be old and obsolete tomorrow... Presumably we're supporting this across multiple versions and we're not testing them all, why not use the Ubuntu default? It probably covers a lot more users anyway and would save us these troubles for when we have actual incompatibilities to consider.
Of course I'm biased though ahahah... I never enjoyed this increasingly common practice of multiple package managers and overly specific dependencies.

**Comment by BrunoMSantos** [comment]
Looks good to me ;)

**Pull request merged**
