### PR TITLE
Test updates

### PR DESCRIPTION
**Pull request by jnikula**
A handful of small updates to testing.

### CODE REVIEW

**Comment by jnikula** [comment]
Hmph, the anonymous symbol naming isn't stable across my local build and github environment:

https://github.com/jnikula/hawkmoth/actions/runs/3937522510/jobs/6735144722#step:5:45

**Comment by BrunoMSantos** [comment]
Nice set of changes.

As for the anonymous symbol names, I get the same as in CI. Given the diff, I'd guess there were some white space / block comment format changes in one of the sources that affected the lines in which the symbols are declared without affecting anything else.

Or do you mean that you get an empty diff locally?

**Comment by jnikula** [comment]
Yeah, it works for me locally, no diff.

**Comment by jnikula** [comment]
So if you run `make update-examples`, `doc/examples.rst` gets modified?

**Comment by BrunoMSantos** [comment]
For the record:
```
$ make test-examples 
test/update-examples.py | diff -u - doc/examples.rst
--- -   2023-01-17 13:32:06.535737291 +0000
+++ doc/examples.rst    2023-01-17 13:20:27.770484185 +0000
@@ -76,7 +76,7 @@
 Output
 ~~~~~~
 
-.. c:namespace-push:: namespace_389c9672145e28f8c68eab264e0e0151
+.. c:namespace-push:: namespace_238163a4c73047a60ccef522ea195193
 
 .. c:autovar:: meaning_of_life
    :file: example-variable.c
@@ -143,7 +143,7 @@
 Output
 ~~~~~~
 
-.. c:namespace-push:: namespace_9584794e5a0db25ddfb9667df05acb55
+.. c:namespace-push:: namespace_fc499782b4098eda1789721fd08742ba
 
 .. c:automacro:: DIE
    :file: example-macro.c
@@ -185,7 +185,7 @@
 Output
 ~~~~~~
 
-.. c:namespace-push:: namespace_0b30866ae613b27ac7441298788043e1
+.. c:namespace-push:: namespace_c8d7b219201e168fc0ac126ec28e5dbf
 
 .. c:autofunction:: frob
    :file: example-function.c
@@ -228,7 +228,7 @@
 Output
 ~~~~~~
 
-.. c:namespace-push:: namespace_b5d96bf2bc4a3cde1211c99e53028049
+.. c:namespace-push:: namespace_6719e1b2c4db0da6ad0361cea0c2742f
 
 .. c:autostruct:: list
    :file: example-struct.c
make: *** [test/Makefile.local:16: test-examples] Error 1
```

**Comment by jnikula** [comment]
D'oh! It's not the anonymous naming, but the Sphinx C domain namespaces, which are based on the testcase filename. With full path.

**Comment by jnikula** [comment]
Force pushed a set with a fix to the namespace issue as the first thing.

**Comment by jnikula** [comment]
> Force pushed a set with a fix to the namespace issue as the first thing.

And now it passes nicely.

**Comment by BrunoMSantos** [comment]
> [...] With full path.

Hmm, that explains it. Looks good to me.

**Pull request merged**
